apps:
  re3-installer:
    command: 'usr/bin/re3-installer'
    plugs:
      - 'home'
      - 'removable-media'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/re3-installer/issues'
description: 'Install GTA III files from ISO or directories for use with re3.'
donation: 'https://buymeacoffee.com/Tatsh'
grade: 'stable'
issues: 'https://github.com/Tatsh/re3-installer/issues'
license: 'GPL-3.0-or-later'
name: 're3-installer'
parts:
  re3-installer:
    build-packages:
      - 'libcdio-dev'
      - 'libiso9660-dev'
      - 'libunshield-dev'
      - 'pkg-config'
      - 'zlib1g-dev'
    cmake-parameters:
      - '-DCMAKE_BUILD_TYPE=Release'
      - '-DCMAKE_INSTALL_PREFIX=/usr'
    plugin: 'cmake'
    source: 'https://github.com/Tatsh/re3-installer.git'
    source-tag: 'v0.2.6'
    source-type: 'git'
    stage-packages:
      - 'libcdio19t64'
      - 'libiso9660-11t64'
      - 'libunshield0'
      - 'zlib1g'
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/re3-installer'
summary: 'Install GTA III files from ISO or directories for use with re3.'
title: 're3-installer'
version: '0.2.6'
website: 'https://tatsh.github.io/re3-installer/'
