name: C/C++ CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y libunshield-dev 
    - name: make
      run: make
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          brew update
          brew install unshield
      - name: make
        run: make
