jobs:
  clang-format:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v7'
      - name: 'Check formatting (clang-format)'
        run: 'clang-format --dry-run src/*.c src/*.h src/tests/*.c'
name: 'QA'
'on':
  pull_request:
    branches:
      - 'master'
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.hpp'
      - '.github/workflows/qa.yml'
  push:
    branches:
      - 'master'
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.hpp'
      - '.github/workflows/qa.yml'
permissions:
  contents: 'read'
