---
concurrency:
  cancel-in-progress: true
  group: '${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}'
jobs:
  tests:
    name: 'Tests'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install dependencies
        run: pipx install cpp-coveralls && sudo apt-get install -y lcov libcmocka-dev libunshield-dev libcdio-dev libiso9660-dev
      - env:
          BUILD_TYPE: '${{ matrix.build-type }}'
        name: Configure
        run: >-
          cmake -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -B "${GITHUB_WORKSPACE}"/build
          --install-prefix "${GITHUB_WORKSPACE}"/build/prefix
          -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON
      - env:
          BUILD_TYPE: '${{ matrix.build-type }}'
        name: Build
        run: cmake --build "${GITHUB_WORKSPACE}"/build --verbose --config "${BUILD_TYPE}"
      - env:
          BUILD_TYPE: '${{ matrix.build-type }}'
        name: Install
        run: cmake --install "${GITHUB_WORKSPACE}"/build --config "${BUILD_TYPE}" --verbose
      - name: Run tests
        run: ctest -VV --test-dir "${GITHUB_WORKSPACE}"/build/src/tests --output-on-failure
      - if: ${{ matrix.build-type == 'Debug' }}
        name: Generate coverage information
        run: >-
          geninfo
          --debug
          --exclude src/tests
          --follow
          --keep-going
          '--include=src/*'
          -b "${GITHUB_WORKSPACE}"
          -o coverage1.lcov
          "${GITHUB_WORKSPACE}"/build
      # - if: ${{ matrix.build-type == 'Debug' }}
      #   name: 'Coveralls'
      #   uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329
      - if: ${{ matrix.build-type == 'Debug' }}
        name: 'Coveralls'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: >-
          coveralls
          -e src/tests
          -i src/env.c
          -i src/env.h
          -i src/extractor.c
          -i src/extractor.h
          -i src/utils.c
          -i src/utils.h
          -i src/installer.c
          -i src/installer.h
          -i src/log.c
          -i src/log.h
          -i src/mkdir_p.c
          -i src/mkdir_p.h
          -i src/support.h
    strategy:
      matrix:
        build-type: [Debug, Release]
  asan-test:
    name: 'Tests (sanitizers)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install tools
        run: sudo apt-get update -y && sudo apt-get install -y libcmocka-dev libunshield-dev libcdio-dev libiso9660-dev
      - env:
          BUILD_TYPE: '${{ matrix.build-type }}'
        name: Configure
        run: >-
          cmake -B "${GITHUB_WORKSPACE}"/build -DCMAKE_BUILD_TYPE="${BUILD_TYPE}"
          -DBUILD_TESTS=ON -DENABLE_ASAN=ON -DENABLE_UBSAN=ON
      - name: Build
        run: cmake --build "${GITHUB_WORKSPACE}"/build --verbose
      - name: Run tests
        run: ctest --test-dir "${GITHUB_WORKSPACE}"/build/src/tests --verbose
    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, RelWithDebInfo]
name: Tests
'on':
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions:
  contents: 'read'
